#
# A ConfigMap spec for openldap slapd that map directly to files under
# /container/service/slapd/assets/config/bootstrap/ldif/custom
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" . }}-replication-config
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
  # replication
  01_syncprov.ldif: |
    # Load syncprov module
    dn: cn=module,cn=config
    objectClass: olcModuleList
    cn: module{0}
    olcModuleLoad: syncprov
  02_serverid-modify.ldif: |
    # Set server ID
    dn: cn=config
    changeType: modify
    add: olcServerID
    {{- include "olcServerIDs" . }}
  03_csyncprov-modify.ldif: |
    # Add syncprov on config
    dn: olcOverlay=syncprov,olcDatabase={0}config,cn=config
    changetype: add
    objectClass: olcOverlayConfig
    objectClass: olcSyncProvConfig
    olcOverlay: syncprov
  04_rep-modify.ldif: |
    # Add sync replication on config
    dn: olcDatabase={0}config,cn=config
    changetype: modify
    add: olcSyncRepl
    {{- include "olcSyncRepls" . }}
    -
    add: olcMirrorMode
    olcMirrorMode: TRUE
  05_bsyncprov.ldif: |
    dn: olcOverlay=syncprov,olcDatabase={2}mdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcSyncProvConfig
    olcOverlay: syncprov
    olcSpSessionLog: 100
  06_brep-modify.ldif: |
    dn: olcDatabase={2}mdb,cn=config
    changetype: modify
    add: olcSyncrepl
    {{- include "olcSyncRepls2" . }}

    dn: olcDatabase={2}mdb,cn=config
    changetype: modify
    add: olcMirrorMode
    olcMirrorMode: TRUE
  # acls
  07_acls-modify.ldif: |
{{- if .Values.customAcls }}
    {{- .Values.customAcls | nindent 4 }}
{{- else }}
    dn: olcDatabase={2}mdb,cn=config
    changetype: modify
    replace: olcAccess
    olcAccess: {0}to *
      by dn.exact=gidNumber=1001+uidNumber=1001,cn=peercred,cn=external,cn=auth manage
      by * break
    olcAccess: {1}to attrs=userPassword,shadowLastChange
      by self write
      by dn="{{ include "global.bindDN" . }}" write
      by anonymous auth by * none
    olcAccess: {2}to *
      by dn="{{ include "global.bindDN" . }}" write
      by self read
      by * none
{{- end }}
