#
# A ConfigMap spec for openldap slapd that map directly to files under
# /container/service/slapd/assets/config/bootstrap/ldif/custom
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" . }}-replication-acls
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ template "openldap.fullname" . }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
  # replication
  00_syncprov-load.ldif: |
    # Load syncprov module
    dn: cn=module,cn=config
    cn: module
    objectClass: olcModuleList
    olcModuleLoad: syncprov.so
    olcModulePath: /opt/bitnami/openldap/lib/openldap
  01_serverid-modify.ldif: |
    # Set server ID
    dn: cn=config
    changeType: modify
    add: olcServerID
    {{- include "olcServerIDs" . }}
  02_rep-modify.ldif: |
    # Add sync replication on config
    dn: olcDatabase={0}config,cn=config
    changetype: modify
    add: olcSyncRepl
    {{- include "olcSyncRepls" . }}
    -
    add: olcMirrorMode
    olcMirrorMode: TRUE
  03_brep-modify.ldif: |
    dn: olcDatabase={2}mdb,cn=config
    changetype: modify
    add: olcSyncrepl
    {{- include "olcSyncRepls2" . }}

    dn: olcDatabase={2}mdb,cn=config
    changetype: modify
    add: olcMirrorMode
    olcMirrorMode: TRUE
  04_syncprov.ldif: |
    dn: olcOverlay=syncprov,olcDatabase={0}config,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcSyncProvConfig
    olcSpCheckpoint: 100 10
    olcSpSessionlog: 50000
  05_syncprov.ldif: |
    dn: olcOverlay=syncprov,olcDatabase={2}mdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcSyncProvConfig
    olcSpCheckpoint: 100 10
    olcSpSessionlog: 55000000
  06_acls-modify.ldif: |
{{- if .Values.customAcls }}
    {{- .Values.customAcls | nindent 4 }}
{{- else }}
    dn: olcDatabase={2}mdb,cn=config
    changetype: modify
    replace: olcAccess
    olcAccess: {0}to *
      by dn.exact=gidNumber=1001+uidNumber=1001,cn=peercred,cn=external,cn=auth manage
      by * break
    olcAccess: {1}to attrs=userPassword,shadowLastChange
      by self write
      by dn="{{ include "global.bindDN" . }}" write
      by anonymous auth by * none
    olcAccess: {2}to *
      by dn="{{ include "global.bindDN" . }}" write
      by self read
      by * none
{{- end }}
