{{- range .Values.customFileSets }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" $ }}-fs-{{ .name }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
{{- if $.Values.extraLabels }}
{{ toYaml $.Values.extraLabels | indent 4 }}
{{- end }}
data:
{{- range .files }}
{{ .filename | indent 2}}: |
{{ .content | indent 4 }}
{{- end}}
---
{{- end }}
