#
# A ConfigMap spec for openldap slapd that map directly to files under
# /custom-schemas
#
{{- if .Values.customSchemaFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" . }}-customschema
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ template "openldap.fullname" . }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
{{- range $key, $val := .Values.customSchemaFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end }}
