{{ if not .Values.global.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openldap.fullname" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ template "openldap.fullname" . }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  LDAP_ADMIN_USERNAME: {{ .Values.global.adminUser | b64enc | quote }}
  LDAP_ADMIN_PASSWORD: {{ .Values.global.adminPassword | b64enc | quote }}
  {{- if .Values.global.configUserEnabled }}
  LDAP_CONFIG_ADMIN_PASSWORD: {{ .Values.global.configPassword  | b64enc | quote }}
  {{- end}}
{{ end }}
