apiVersion: v1
kind: Service
metadata:
  name: {{ template "openldap.fullname" . }}-headless
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ template "openldap.fullname" . }}
spec:
  ports:
  {{- if .Values.service.enableLdapPort }}
  - port: {{ .Values.global.ldapPort }}
    name: ldap-port
    targetPort: ldap-port
  {{- end }}
  {{- if .Values.service.enableSslLdapPort }}
  - port: {{ .Values.global.sslLdapPort }}
    name: ssl-ldap-port
    targetPort: ssl-ldap-port
  {{- end }}
  clusterIP: None
  selector:
    app.kubernetes.io/component: {{ template "openldap.fullname" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  sessionAffinity: None
