{{- if and ( .Values.initTLSSecret.tls_enabled ) (hasKey .Values.initTLSSecret "secret") (ne .Values.initTLSSecret.secret "") ( .Values.initTLSSecret.tls_gencert ) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.initTLSSecret.secret }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
{{- if $.Values.extraLabels }}
{{ toYaml $.Values.extraLabels | indent 4 }}
{{- end }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "openldap.gen-certs" . ) | indent 2 }}
{{- end }}
