name: Test-Other
on:
  workflow_call:
jobs:
  qualif:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Run custom action
      # Use the location in the repository (without action.yml)
      uses: ./.github/actions/setup
      with:
        install-chaos: false
    - name: Create namespace
      shell: bash
      run: |
        kubectl create namespace ds
    - name: Deploy OpenLDAP/HA, disabled LDAP port
      shell: bash
      run: |
        helm install openldap -n ds --create-namespace -f .bin/disableLdapPort.yaml .
        kubectl --namespace ds get events --watch &
        kubectl --namespace ds rollout status sts openldap; ec=$?
        kubectl --namespace ds logs -l app.kubernetes.io/name=openldap --all-containers=true --timestamps=true --prefix=true --since=6h --tail=-1 --ignore-errors
        exit $ec
    - name: Test access to OpenLDAP database
      shell: bash
      run: |
          echo "Test access to OpenLDAP database"
          nc -vz localhost 30636 || exit 1
          LDAPTLS_REQCERT=never ldapsearch -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=example,dc=org'
    - name: Write test to OpenLDAP database
      shell: bash
      run: |
          echo "Write test to OpenLDAP database"
          LDAPTLS_REQCERT=never ldapadd -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -f .bin/simpleUser.ldif
    - name: Read from OpenLDAP database
      shell: bash
      run: |
          echo "Read from OpenLDAP database"
          sleep 10
          if [ $(grep "numResponses" $(LDAPTLS_REQCERT=never ldapsearch -o nettimeout=20 -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=example,dc=org') | cut -d ":" -f 2 | tr -d ' ') -lt 3 ]; then exit 1 ; fi
