name: Test-SingleNode
on:
  workflow_call:
jobs:
  qualif:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Setup Kind/K8S Cluster
      uses: ./.github/actions/setup
      with:
        install-chaos: false
    - name: Create namespace
      shell: bash
      run: |
        kubectl create namespace ds
    - name: Create a secret to update later on
      shell: bash
      run: |
        kubectl --namespace ds create secret generic my-super-secret --from-literal=LDAP_ADMIN_PASSWORD=Not@SecurePassw0rd --from-literal=LDAP_CONFIG_ADMIN_PASSWORD=Not@SecurePassw0rd
    - name: Deploy OpenLDAP single node
      shell: bash
      run: |
        helm install --namespace ds openldap -f .bin/singleNode.yaml .
        kubectl --namespace ds get events --watch &
        kubectl --namespace ds rollout status sts openldap; ec=$?
        kubectl --namespace ds logs -l app.kubernetes.io/name=openldap --all-containers=true --timestamps=true --prefix=true --since=6h --tail=-1 --ignore-errors
        exit $ec
    - name: Test OpenLDAP database via TLS
      uses: ./.github/actions/tls-access
      with:
        port: 30636
        bind_dn: 'cn=admin,dc=singlenode,dc=org'
        base_dn: 'dc=singlenode,dc=org'
