name: Qualif

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-ci-singlenode:
    uses: ./.github/workflows/ci-singlenode.yml
  call-ci-other:
    uses: ./.github/workflows/ci-other.yml
  call-ci-ha:
    uses: ./.github/workflows/ci-ha.yml
