name: GitHub Pages

on:
    release:
      types: # This configuration does not affect the page_build event above
        - created
        - updated
        - prereleased
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Release chart on gh-pages
        shell: bash
        run: |
          set -Eeuo pipefail
          set -x
          remote_name="origin"
          main_branch="master"
          target_branch="gh-pages"
          build_dir="dist"
          repo_uri="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          cd "$GITHUB_WORKSPACE"/openldap
          helm package --destination ../.. .
          cd "$GITHUB_WORKSPACE"
          git checkout "$target_branch"
          mv ../*.tgz .
          helm repo index .
          git add -A
          git commit -m "updated GitHub Pages"
          if [ $? -ne 0 ]; then
              echo "nothing to commit"
              exit 0
          fi
          git remote set-url "$remote_name" "$repo_uri"
          git push --force-with-lease "$remote_name" "$target_branch"
